import type { Metadata } from "next";
import "./globals.css";
import { Syne } from "next/font/google";
export const syne = Syne({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Figbruary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${syne.className} flex flex-col justify-between items-center`}
      >
        {children}
      </body>
    </html>
  );
}
