import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {Syne} from 'next/font/google'

export const syne = Syne({subsets: ['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${syne.className} flex flex-col justify-between items-center`}>
        {children}
      </body>
    </html>
  );
}
